### ISSUE TITLE
pandas version and question

### ISSUE THREAD

**Issue by nandobonf** [damianosmel/GenOtoScope#1]
Dear authors, 
the command:
`pyensembl install --release 75 --species human`
does not work with pandas==0.25.3 (as defined in the requirements file). 
It throws:
`TypeError: parser_f() got an unexpected keyword argument 'on_bad_lines'`

Should be fixed with a newer version of pandas.

Another question, not related to the issue above: why using the whole megSAP for VEP annotation? the docker image is extremely slow and heavy.

**Comment by damianosmel** [comment]
Hi,

which pyensembl version did you use? The [one](https://github.com/damianosmel/GenOtoScope/blob/b94913f6d624fa1a5005716e4783aef35ae7c146/genotoscope_env_requirements.txt#L10) found in the requirements works with the pandas specified by the same requirements file.

About using the whole megSAP, I guess, **for the time being**, you can add it as a feature in the wish list. 

Thanks!

**Comment by nandobonf** [comment]
Yes, the pyensembl version is the one from the requirements (1.9.4).
Also when running`pyensembl install --release 75 --species human` in a fresh new conda env with just pyensembl=1.9.4 and  pandas=0.25.3 I get the error: 
`AttributeError: module 'numpy' has no attribute 'bool'`

Thanks for the reply.

**Comment by damianosmel** [comment]
Hey, I feel I have found the issue. So, after having created a clean conda environment and follow my own [guide](https://github.com/damianosmel/genotoscope_wiki/wiki/Python-Environment), I got an error running the `pyensembl install --release ..`  line.

The error that I got was with the [polars](https://www.pola.rs/) library. I guess, somehow is install by the command: `pip3 install -r genotoscope_env_requirements.txt` as a dependency of the pyensembl.

Then, I have updated the versions of **only** the pyensembl and pandas and the command sequence found in my [guide](https://github.com/damianosmel/genotoscope_wiki/wiki/Python-Environment) and it works!

I attach here the updated genotoscope_env_requirements.txt.
Please follow the guide found in the wiki and in the previous paragraph and see if with the new versions of the two packages you get the installation to work.
[genotoscope_env_requirements.txt](https://github.com/damianosmel/GenOtoScope/files/10310474/genotoscope_env_requirements.txt)

Please let me know it works also for you, so I update the requirements.txt in the main repository. Thanks!

**Comment by damianosmel** [comment]
Hey @nandobonf did my suggestion work also for you?
I am asking so I can close the issue, thanks :)

**Comment by nandobonf** [comment]
Hi, apologies for the very late reply. The problem is fixed, thanks. I'm facing other problems but I will eventually open a new issue. Thanks!

**Comment by damianosmel** [comment]
Hi, I have added the commit: [253aebd]( https://github.com/damianosmel/GenOtoScope/commit/253aebd1b822daf437de39deff68852b538e799b) to resolve and close this issue.
